-- This migration is intentionally empty.
--
-- The original migration.sql for 20260810153158_add_course_content_files
-- was corrupted (accidentally overwritten with an unrelated build cache file).
--
-- Investigation confirmed all schema changes implied by this migration's name
-- (courseId, coverUrl, order, pdfUrl, fileSizeBytes, mimeType on Article/Video/Resource)
-- were already applied by prior migrations:
--   - 20260808185751_add_system_settings
--   - 20260810115058_update_schema
--
-- The live database and prisma/schema.prisma are already in sync with no
-- remaining diff attributable to this migration, so it is left empty to
-- preserve migration history ordering without re-applying existing changes.